# Generated by Django 5.2.7 on 2025-11-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0006_usuario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('experiencia', models.TextField()),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.persona')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_estudios', models.CharField(choices=[('PR', 'Primaria'), ('SE', 'Secundaria'), ('UN', 'Universidad'), ('OT', 'Otro')])),
                ('institucion_actual', models.CharField(max_length=255)),
                ('experiencia_laboral', models.TextField(blank=True, null=True)),
                ('ciudad_residencia', models.CharField(choices=[('USH', 'Ushuaia'), ('RGA', 'Río Grande'), ('TLH', 'Tolhuin')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('jerarquia', models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Coordinador'), (3, 'Mesa de Entrada'), (4, 'Docente'), (5, 'Estudiante')])),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tutor', models.CharField(choices=[('AC', 'Academico'), ('PE', 'Personal'), ('LA', 'Laboral'), ('OT', 'Otro')])),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('disponibilidad_horaria', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
            },
        ),
        migrations.CreateModel(
            name='TutorEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.estudiante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.tutor')),
            ],
            options={
                'verbose_name': 'Tutor/Estudiante',
                'verbose_name_plural': 'Tutor/Estudiante',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Usuario/Rol',
                'verbose_name_plural': 'Usuarios/Roles',
            },
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.CheckConstraint(condition=models.Q(('jerarquia__gte', 1), ('jerarquia__lte', 5)), name='rol_jerarquia_entre_1_y_5'),
        ),
        migrations.AlterUniqueTogether(
            name='tutorestudiante',
            unique_together={('tutor', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('usuario', 'rol')},
        ),
    ]
