# Generated by Django 5.2.7 on 2025-11-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('roles', '0001_initial'),
        ('usuario', '0004_remove_usuario_activo_remove_usuario_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariorol',
            options={'verbose_name': 'Usuario/Rol', 'verbose_name_plural': 'Usuarios/Roles'},
        ),
        migrations.RenameField(
            model_name='usuariorol',
            old_name='rol_id',
            new_name='rol',
        ),
        migrations.RenameField(
            model_name='usuariorol',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='rol',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('usuario', 'rol')},
        ),
    ]
