# Generated by Django 5.2.7 on 2025-11-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_usuariorol_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorestudiante',
            options={'verbose_name': 'Tutor/Estudiante', 'verbose_name_plural': 'Tutor/Estudiante'},
        ),
        migrations.AlterUniqueTogether(
            name='tutorestudiante',
            unique_together={('tutor', 'estudiante')},
        ),
    ]
