# Generated by Django 5.2.7 on 2025-11-04 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='id_inscripcion',
            field=models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcion'),
        ),
    ]
