# Generated by Django 5.2.7 on 2025-11-04 14:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='Activo', max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_comision', models.ForeignKey(db_column='id_comision', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_comision', to='cursos.comision')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_curso', to='cursos.curso')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_estudiante', to='roles.estudiante')),
                ('id_tutor', models.ForeignKey(blank=True, db_column='id_tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_tutor', to='roles.tutor')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripcion',
            },
        ),
    ]
