# Generated by Django 5.2.7 on 2025-11-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id_comision', models.AutoField(primary_key=True, serialize=False)),
                ('dias_horarios', models.TextField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cupo_maximo', models.IntegerField(default=20)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Finalizada', 'Finalizada')], default='Abierta', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('edad_minima', models.IntegerField(blank=True, null=True)),
                ('requisitos', models.TextField(blank=True, null=True)),
                ('contenido_multimedia', models.URLField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ComisionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_comision', models.ForeignKey(db_column='fk_id_comision', on_delete=django.db.models.deletion.CASCADE, to='cursos.comision')),
                ('fk_id_docente', models.ForeignKey(db_column='fk_id_docente', on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'unique_together': {('fk_id_comision', 'fk_id_docente')},
            },
        ),
        migrations.AddField(
            model_name='comision',
            name='docentes',
            field=models.ManyToManyField(related_name='comisiones_asignadas', through='cursos.ComisionDocente', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='comision',
            name='fk_id_curso',
            field=models.ForeignKey(db_column='fk_id_curso', on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='materiales_cursos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fk_id_comision', models.ForeignKey(db_column='fk_id_comision', on_delete=django.db.models.deletion.CASCADE, to='cursos.comision')),
                ('fk_id_docente', models.ForeignKey(db_column='fk_id_docente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
    ]
