# Generated by Django 5.2.7 on 2025-11-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_activo_remove_usuario_contrasena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(blank=True, null=True),
        ),
    ]
